### ISSUE TITLE
Default voltage 3.5v?

### ISSUE THREAD

**Issue by kizniche** [mk-fg/sht-sensor#1]
> For both the tool and module, also be sure to check/specify correct voltage (default is '3.5V')

Why is the default voltage 3.5 volts and not the standard for low voltage electronics, 3.3 volts?

Am I correct in assuming a 3.3-volt system will not yield a correct measurement calculation?

**Comment by kizniche** [comment]
Additionally, why is the typical power supply listed as 3.3 volts on the [datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/Humidity_and_Temperature_Sensors/Sensirion_Humidity_and_Temperature_Sensors_SHT7x_Datasheet_V5.pdf)

> Page 2

| Parameter | min | typ | max |
| --- | --- | --- | --- |
| Power supply DC-volts | 2.4 | 3.3 | 5.5 |

yet there isn't a coefficient listed for 3.3 volts.

> Page 8

| VDD | d<sub>1</sub>(°C) | d<sub>1</sub>(°F) |
| --- | --- | --- |
| 5V | -40.1 | -40.2 |
| 4V | -39.8 | -39.6 |
| 3.5V | -39.7 | -39.5 |
| 3V | -39.6 | -39.3 |
| 2.5V | -39.4 | -38.9 |

Does this mean that the table is purposefully missing 3.3 volts because it's the typical voltage, and using `--voltage=3.3V` will yield the correct measurement, or will the measurement be incorrect in all cases when using 3.3 volts?

**Comment by kizniche** [comment]
BTW, I recently integrated the use of this module into a project of mine, [Mycodo](https://github.com/kizniche/Mycodo/tree/master/3.5) and am just trying to clarify this in order to obtain the most accurate measurements possible.

**Comment by mk-fg** [comment]
> Why is the default voltage 3.5 volts and not the standard for low voltage electronics, 3.3 volts?

I think looked at page-8 table that you copied above and picked closest coefficient that was listed there as default, which was 3.5V.

Don't remember whether I did the calculations to see how much it'll be off depending on these numbers (they are trivial, all listed in the datasheet and in the code), but suspect that given only fraction-of-a-degree effect of these, which should be good enough for vast majority of cases, didn't bother adding special warning about that anywhere.

Plus, anyone who cares that much about precision should probably check datasheet, do extensive testing in controlled conditions and spot the thing easily anyway.

> Am I correct in assuming a 3.3-volt system will not yield a correct measurement calculation?

Yeah, I think they'll be slightly off because of that, but not by much, iirc.

With Raspberry Pi in mind, guess 5V can be used, but - esp. with cheap power supplies - it's also usually not 5V but 4.5V-5.2V (with most giving out ~5.2V, I think, going down with the load).
Not sure if 3.3V is more reliable there, and if so, it might still be better option, even with 3.5V coefficient.

> yet there isn't a coefficient listed for 3.3 volts.

Yeah, a bit weird.

> Does this mean that the table is purposefully missing 3.3 volts because it's the typical voltage

I wouldn't go as far as to claim that it's intentional omission to make people's lives harder, but seem to be quite unfortunate, indeed.

I'd guess that they didn't do the testing and derived the coefficient with that voltage, but probably because no one thought about it at the time, and typical voltage was only filled-in when datasheet was compiled.

There are of course ways to derive the number yourself or you can contact the vendor about it, and then pass the right coefficients to the module - I should've implemented some way to do that.

**Comment by mk-fg** [comment]
> and using --voltage=3.3V

Also: you can't use '3.3V' with current code, as '3.3V' is not actually a free-form real number with 'V' appended, but a VDD spec from the tables, and there's no '3.3V', so using that should raise error.

https://github.com/mk-fg/sht-sensor/blob/master/sht_sensor/sensor.py#L187-L198

**Comment by kizniche** [comment]
Thank you for the detailed response.

I suppose -39.66°C would be a good estimate for 3.3V. If the user wants to be more accurate, they probably should invest in a regulated power supply at the voltages supported by the driver or a more accurate sensor.

**Comment by mk-fg** [comment]
Ah, yeah, see now that it's just a flat offset, and the difference will be 0.04 C, which is definitely negligible in most cases (as air convection will make a much larger fluctuations), and ~20x outside of 0.8 C sensor's typical precision range.

So it's more of a puzzle as to why they've bothered to make that coefficient voltage-dependent at all - average of ones for whole voltage range would've given same results, hurting precision only a tiny bit.

Will put a note on that in the README, I guess.

**Comment by AncientGate** [comment]
I dont agree, i think its just simpler and better to add -39.66 into code of driver, finally its just one place.
I do this always locally , but i think it will nothing harm if add this value direct into driver code.
Why not? one line will not make it problems at all :)
The one who need it more precise will know how to do the rest about power supply, but if there are requirements to use standard 3.3V, so why not offer this in driver, without a necessity to modify code of driver ? :) IMHO.

**Comment by mk-fg** [comment]
Yeah, that's what I considered doing at first.

But then my logic went like this: ok, add that, then code comment as to where that value came from (so people comparing tables for their SHT7x-like sensor won't get confused), then 5 lines to readme explaining that voltage value is either from tables or special "3.3V" (and where it came from), which is also default, and a line to option description...

At which point, if it's not table values anyway, why not make voltage a float and use a linear formula for d1?
But it's probably not linear, and that'd be more weird to understand and replace for different-table sensors...
And then precision - which was kinda the point - and obviousness of how it works goes out of the window.

At which point, why not just draw a line (and it has to be drawn somewhere) on what the table says , as 0.04 vs 0.8 just does not matter.

Hence that comment in the README instead of that original idea.
I see your point, but meh, whatever, looks more straightforward this way to me.
