### ISSUE TITLE
 Tuning SHT75 Sensor 

### ISSUE THREAD

**Issue by FredsterCode** [mk-fg/sht-sensor#2]
Hi, 
I really appreciate the python library for the SHT75 sensor. However the temperature results I'm getting are routinely a little high and I cant yet figure out why. At the moment all I have as references are 3 separate temperature and humidity monitoring devices. Consumer products from Maplin Electronics so not seriously accurate but hopefully not too off the mark. 
The readings I'm getting from the SHT75 ( I have two ) are constantly 2 to 4 degrees higher than the other consumer units show.  One SHT75 is 2 degrees higher and the other is 4 degrees higher.

I'm using a Raspberry Pi 2 and attaching the SHT75 to the 3.3V, GND, a CLK pin, and a DATA pin.  There is a 10K pull up resistor on the Data pin per the data sheet pdf from Sensirion. 

Is your setup any different ? 
Have you by any chance developed a way to look at the register? It may be the heater is turned on ! but that seems strange.
The data sheet also refers to self-heating if measurements are too frequent.  I'm measuring at 10 second intervals so that should be OK.  I have varied it from 5 seconds to 10 seconds and not seen any noticeable difference.
Is it possible the device should be turned off (power removed) between readings? 
Thanks in advance.

**Comment by mk-fg** [comment]
Don't think I can be of much help here, unfortunately.

I'm not a metrologist, don't know much about what's inside these sensors and what can affect them beyond what is common knowledge.
Only worked with these on hobby projects and one-off jobs, where high accuracy wasn't a concern.
So please don't take my word as any kind of reliable source of info on the subject.

Obvious thing to check - which you've probably covered, but guess I'll mention it anyway - is that when you compare results, sensors are right next to each other in exactly same conditions, and measurements are taken at the same time.
Even room temperature can vary by few degrees for sensors a meter or two apart, I think, not to mention direct sunlight, steam/vapor from coffee mug below or whatever other huge factors.

Not sure if wire temperature should affect these sensors much (i.e. how well they're shielded from that), but it sure does a lot with e.g. simple thermistors.
So I'd also suggest trying to compare data from these with wires in the same env as sensor, as e.g. thermistor with long wire on the outside vs inside can easily give few degees of difference.

Then I'd also check the voltage on VDD/GND pins - RPi should probably have stable 3.3V, but might be still worth checking, as that might be off due to e.g. bad wire/contacts, and should affect the measurements, not sure if by that much though (and yet still work).

Currently have DHT22 and SHT75 sitting ~0.5m apart, difference seem to be 0.2 C (26.85 vs 27.02), connected to diff boards, and one on ~2m wire, so looks close enough to me.
Wrt sensor defects - with three DHT22 sensors next to each other, had one that was always about 2C higher than others, one DHT22 consistently gives random -5C delta every once in a few minutes when it's below zero, etc... but maybe SHT75 shouldn't have such quirks.

> Is your setup any different?

No, same stuff, though I did connect VDD to 5V instead of 3.3V in some cases.

> Have you by any chance developed a way to look at the register?

No, never needed it, really.
All commands for that are in datasheet though, so you can probably add that yourself rather easily.

Don't think sensor should keep state of the heater bit on power-cycling, so I think it's gotta be off for sure, wouldn't bother to implement anything to check it.

>  Is it possible the device should be turned off (power removed) between readings?

Fairly sure it should not be the case - haven't seen anything like that in the datasheet, seem to work fine without that, and it doesn't make sense to me on many levels.

> The data sheet also refers to self-heating if measurements are too frequent.

I'd think that it'd refer to taking measurements in a tight loop, like 1/s or whatever device itself permits, but don't really know.
Few seconds sound fine, and indeed easy to rule-out via simple test (where t doesn't go up) like you did.

**Comment by FredsterCode** [comment]
I have (blushing) found that the distance from the Raspberry Pi is be a big factor in the odd readings. Heat from the Pi caused the issue !! . Still some fine tuning remaining I believe though.
Many thanks for the reply. You have given me some insights that are very interesting.

Another question. 
How are you physically arranging the sensor and the wires and the pull up resistor. I have not yet found a nice and cost effective way to connect things. The sensor and board package are quite delicate. There are professional enclosures with nice cables but they are expensive. The pull up is awkward to add in between the flying leads and I cant see another way to add the resistor ! 
Thanks again for the reply.

**Comment by mk-fg** [comment]
Um, I just solder resistor to the wires near the board (or whatever) connector.
Always connected these to wires (e.g. 4-wire 1mm ribbon cable), once by soldering wires to leads directly, but other times by soldering something like PBD1.27-10 ( http://www.promelec.ru/UPLOAD/2013/11/13/131186.jpg ) and then plugging sensor into that.
And then you can solder pull-up to any place on that cable.

Looks like a rather obvious option though, so maybe I don't understand constraints/requirements that you have (e.g. have to solder thing to PCB or something like that).

With RPi and short-ish cable (not meters of it), don't think you need to bother with pull-ups at all, as RPi has internal (~50-60K) pull-ups, which can easily be enabled from software.
Iirc they worked fine with all sorts of sensors and devices for me, including this one.
If you need pure-python code to enable them (via /dev/mem), can grab it here - https://github.com/mk-fg/fgtk/blob/master/rrd-sensors-logger#L923-L949 (it's for RPi only, of course, as it writes stuff to SoC-specific registers).

**Comment by FredsterCode** [comment]
No pull-up is a nice idea. Thanks. I'll try that out. Makes the whole physical building process much simpler. I have just about enough soldering skill to get some leads on the springy legs of the SHT75 board. The wires have female connectors at the other end. ( originally female to female leads that I cut in half) 
Found this for the RPi pull up setting. http://makezine.com/projects/tutorial-raspberry-pi-gpio-pins-and-python/

import RPi.GPIO as GPIO
GPIO.setup(24, GPIO.IN, pull_up_down = GPIO.PUD_UP)

Looks like that will do the trick. Try it tomorrow.
Many thanks for the help.

**Comment by mk-fg** [comment]
>  GPIO.setup(24, GPIO.IN, pull_up_down = GPIO.PUD_UP)

Yeah, should work too, or you can also use "gpio" binary from wiringpi.
This module uses /sys/class/gpio/ interface though, exporting pins there might or might not reset pull-up/down registers, not sure...
