### ISSUE TITLE
SHT1x sensor error with voltage=5V

### ISSUE THREAD

**Issue by kizniche** [mk-fg/sht-sensor#4]
Reference [Mycodo issue #162](https://github.com/kizniche/Mycodo/issues/162)

Issue with using the sht-sensor module with voltage=5V for SHT1x sensor.

[The user mentions other voltages work](https://github.com/kizniche/Mycodo/issues/162#issuecomment-267648750).

I noticed the [SHT1x module](https://github.com/practicalarduino/SHT1x) doesn't have a voltage parameter. Should SHT1x sensors not use the voltage parameter, or was this just the design of the module to do without that variable?

**Comment by mk-fg** [comment]
I think I've had SHT75 connected to BBB somewhere, will check, though that value isn't really treated differently here either, just used as key for dict here - https://github.com/mk-fg/sht-sensor/blob/master/sht_sensor/sensor.py#L188-L193


> I noticed the SHT1x module doesn't have a voltage parameter. Should SHT1x sensors not use the voltage parameter, or was this just the design of the module to do without that variable?

I think it's just that SHT1x is made for Arduinos, which are universally powered from 5V, unlike e.g. RPi/BBB and other ARM boards, which usually have 2-3 different voltage levels in there (e.g. 5V power line/usb/peripherals, 3.3V GPIO, 1.x for actual SoC).

https://github.com/practicalarduino/SHT1x/blob/master/SHT1x.cpp#L38

**Comment by mk-fg** [comment]
Was due to passing non-exact strings like '5.0V' instead of '5V', apparently, with latter being essentially table/enum values.

As also mentioned in the other linked thread, with sht-sensor==16.12.0, there's now ShtVDDLevel enum, which can be used to avoid this kind of errors by making interpreter do earlier checking, as also suggested in the updated README.

> > I noticed the SHT1x module doesn't have a voltage parameter.

> I think it's just that SHT1x is made for Arduinos
> https://github.com/practicalarduino/SHT1x/blob/master/SHT1x.cpp#L38

One additional weird thing about that code is that it uses -40.0 conversion coefficient, while datasheets for both SHT1x and SHT7x say that it should be -40.1 for C and -40.2 for F.
Shouldn't matter much, as it's +/- 0.3C (iirc) for this sensor readings anyway, just strange.
