### ISSUE TITLE
Ack failed

### ISSUE THREAD

**Issue by ghost** [mk-fg/sht-sensor#7]
Hi!
I'm working on a project with different sensors and i'm using the Sht15 with Intel Edison and the Gpio Block  https://www.sparkfun.com/products/13038.

I'm running Python 2.7 to use the library sht-sensor and i tried to connect the sensor Sck - Data to any gpio pins but I always get this error : 

"raise ShtCommFailure('Command ACK failed on step-1')
sht_sensor.sensor.ShtCommFailure: Command ACK failed on step-1"

I also connected 3.3V to Vcc and Gnd to Gnd.

Do you have any ideas to solve the problem? Sorry i'm really new to it and i never did electronic programming before...

Thank you for your time and consideration,

Cheers

Anthony

**Comment by mk-fg** [comment]
Hi,

It's a very general error saying "sensor doesn't seem to respond at all", see e.g. same thing here:
https://github.com/mk-fg/sht-sensor/issues/5#issuecomment-269100747

Same as in the linked comment, I'd suggest double-checking that you can e.g. control/light-up LED on that same pin, to make sure that it works at all and you got the number correctly.
You should be able to control pins easily via sysfs, e.g. `cd /sys/class/gpio && echo 17 > export && echo high > gpio17/direction`.

**Comment by ghost** [comment]
Thank you for the answer

I tested all the pins by blinking a LED and it's working.
I also looked at the closed issue and my sht15 has a pull up resistor.

I'm using Gpio 14 (mraa 36) as Data and Gpio182 (mraa 0) as Sck and i tried closer one 

Cheers

**Comment by mk-fg** [comment]
"closer one" shouldn't really matter, it's just a note on that particular issue where it seem unlikely that person picked two pins on the opposite sides of pin header vs simple mistake with numbers or a copy-pasting error.

**Comment by ghost** [comment]
I tried to connect the sensor to any pins again but still the same error 

Do you think that the problem is the sensor?

Cheers

**Comment by mk-fg** [comment]
Not sure what else to suggest though.

Two unlikely things that might be an issue:

- Too high clock rate, which you can adjust by changing this line:

    https://github.com/mk-fg/sht-sensor/blob/2cd3d3e/sht_sensor/sensor.py#L135

    To e.g. `time.sleep(0.05)` or something longer like that, to make sure chip on the other side can handle it.
    Though as also mentioned in #6, it seem a bit unlikely that python is that fast ;)

- Some problem with the sensor, which I guess you can check by connecting oscilloscope to the same pins, and making sure that all the signals there are correct, crisp, corresponding to datasheet, and it's just sensor that doesn't respond for whatever reason.


> Do you think that the problem is the sensor?

In my experience tinkering with these things, that's extremely unlikely, and pretty much always some kind of wiring or code error, but as with any electronics, there are certainly ways to damage or render it inert otherwise, I'd just assume that it's not though, unless there's clear evidence to contrary from oscilloscope or other identical sensor works in same socket/configuration.

**Comment by mk-fg** [comment]
> Too high clock rate, which you can adjust by changing this line:

I've just added frequency settings (as per #6), so maybe try these out as well.
Described here: https://github.com/mk-fg/sht-sensor/#max-bit-banging-frequency-control

If slowing things down works, then guess you have some capacitance in the connection between board pins and the sensor, though no idea where that might come from except long wires.

Otherwise, don't think I have anything else to suggest trying, but feel free to re-open if there's any indication that code is to blame, or you have any suggestions wrt that.
Also, would be interested to know what might be the issue there myself, so please drop a comment if you'll figure it out, maybe worth putting in the README or suggesting to check/try in similar cases.

**Comment by ghost** [comment]
Hi, 

Thanks i will look at it tomorrow and update. If I find anything i will drop a comment.

Cheers

**Comment by mk-fg** [comment]
Come to think of it, with --max-freq like 20Hz and good reactions, you can catch bits blinking on the LED connected to same pins - no need for oscilloscope ;)
Though maybe that's still a bit too fast...

**Comment by ghost** [comment]
Hi,

After trying what you said i still get the same error.

for Sck = 10 and Data = 4 
If i put sudo sht -t 10 4 it fails at step 1
if i put sudo sht -t 4 10 it fails at step 2

I also tried with the commands you put.

Cheers,

**Comment by mk-fg** [comment]
Shows that level was constant high in one case and constant low in the other, while sensor should change it with SCK ticks.
As you know that there should be a pull-up on one of these, can probably check whether there's some contact issue with multimeter - should measure pull-up between Vcc and DATA pins if both are connected.
But `¯\_(ツ)_/¯`

**Comment by ghost** [comment]
Hi,
Update : now it always fails at step 2..

**Comment by mk-fg** [comment]
Might mean that instead of constant "1" voltage level it now measures constant "0", or that the pin is "floating" (i.e. not connected to anything).
Check the code and/or datasheet to see how it's supposed to behave.

If you can't measure the level on the SCK/DATA pins and confirm whether they operate correctly and it's sensor that doesn't respond, I'd suggest finding and testing some other driver for the thing, at least - can be some bug or incompatibility here after all.

Wrt measuring - given that you seem to have "1" or "0" on same pin (presumably) at different times, definitely would (again) suggest checking if you can measure pull-up resistance there, as that pin should never be "floating", which kinda seem to be the case here, and probably means that you just have lack of contact somewhere (and "1" or "0" is somewhat random due to leftover current or fields affecting the conductor).

Lacking oscilloscope, you can also connect sensors' SCK/DATA to pins (on same or other board) in "input" state and just sample voltage over time on these, to check whether it's command that doesn't get sent or lack of response from sensor, or maybe both/neither.
Can be implemented as a trivial loop, sampling level over and over as fast as possible, recording it along with the timestamp, to line up with when you run measurement routine through this module.
